### ISSUE TITLE
add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [PlanetCentral/FortranRunner#1]
I suggest adding the topics `fortran`, `vscode`, `visual-studio-code` in the About section at https://github.com/PlanetCentral/FortranRunner

**Comment by PlanetCentral** [comment]
> I suggest adding the topics `fortran`, `vscode`, `visual-studio-code` in the About section at https://github.com/PlanetCentral/FortranRunner

Thank you! I will be doing that soon.
